# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'covidTracing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for covidTracing
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'RadarSDK', '~> 3.0.0'
  pod 'Firebase/Database'

  
  
end
